### ISSUE TITLE
Bad error when default_namespace is empty or incorrect

### ISSUE THREAD

**Issue by larryfenn** [associatedpress/datakit-gitlab#12]
@chrislkeller was starting up a project and received an unhelpful error:

```
...datakit gitlab integrate
Git repo found, creating Gitlab project
list index out of range
```

Need to continue the work from #2 and #3 and replace this with a better error message.

**Comment by chrislkeller** [comment]
For me, I think this came when I had the incorrect GitLab creds in the `config.json` file for the plugin. Once I adjusted, everything was disco.

**Comment by larryfenn** [comment]
3DSia+;3NN]2`!

**Comment by larryfenn** [comment]
be95a99247be4f133027f252ca08e27c5c66dbd6
